name: Bicep Deploy

permissions:
  id-token: write
  contents: read

# Controls when the action will run. This workflow can be triggered manually from the GitHub UI.
on:
  workflow_dispatch:
    inputs:
      env_variables_path:
        description: This is the file that points to the loades env variables for the required deployment
        required: true
        default: env.json
      main_bicep_file_path:
        description: This is the bicep file that will be deployed. it references all the Bicep Modules.
        required: true
        default: main.bicep
      bicep_parameters:
        description: Path to parameters file (leave empty if not used)
        required: false
      resourceGroupName:
        description: The name of the Resource Group that you are going to create.
        required: true
      resourceGroupLocation:
        description: What region are you deploying your application too?
        required: true
        default: 'East US'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  TestingOutProcess:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Clone down Example Repository 
      uses: actions/checkout@v3
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Run Custom Bicep Action
      uses: ./bicep-deploy
      with:
        CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Display Contents of Workspace
      shell: bash
      run: ls -ltra; ls -ltra modules

    - name: Load Tags
      uses: ./load_tags
      with:
        jsonFilePath: ${ inputs.env_variables_path }

    - name: Test Usage
      shell: bash
      run: |
        echo "We are testing that the load tags action allows for variables to persist"
        echo $DUMBY_NAME